apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "helm.name" . }}
  name: {{ include "helm.name" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    {{- with .Values.service.ports }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
